- cmd/oci/oci.go
- pkg/builddocker/context.go
On certain linux systems, `.docker/config.json` and `contexts` aren't present.  This PR attemps to load it directly in such systems and if it fails & questions user if they've Docker installed. 
Also, removes print statements from pkg as we don't want pkgs to log (without being configurable when we do)
> Fix docker load on systems where context isn't in ~/.docker

- cmd/dockerfile/df.go
- cmd/oci/oci.go
Fixes platform bug for `bsf oci` cmd and `bsf df` cmd
> fix: platform bug

- flake.nix
Switching flake to use no cc(gcc,etc) to reduce the dependencies fetch to download bsf binary.
> Modify flake to use no cc

- .vscode/launch.json
- pkg/git/git.go
When project isn't at git repo's root, we initialised git again despite the project/directory being part of a git repository already. This PR aims to fix that bug. This might be our first step to help with monorepo setups
> [fix] when project isn't at git repo root

- cmd/oci/oci.go
- pkg/oci/skopeo.go
load podman lets the user load there oci images in podman
uses: 
`bsf oci dev --load-podman`
- [✅ ] Tested locally 
```
warning: Git tree '/home/holiodin/bsf' is dirty
Generating artifacts...
Build completed successfully, please check the bsf-result directory
Loading image to podman...
Getting image source signatures
Copying blob 4cd11ea234bf done   | 
Copying blob 273721342111 done   | 
Copying blob 693a8385a860 done   | 
Copying blob 87ca5b94847d done   | 
Copying blob 9e3ac58ba8ca done   | 
Copying blob 63d7561148dc done   | 
Copying blob 566cacc0e826 done   | 
Copying blob f4909d4bd075 done   | 
Copying blob 51354d3d8115 done   | 
Copying config c71ae52a26 done   | 
Writing manifest to image destination
Image ttl.sh/buildsafe/goapp:dev loaded to podman
holiodin@fedora:~/bsf$ podman …
```
> load-podman

- .envrc
- cmd/cmd.go
- cmd/direnv/direnv.go
- cmd/direnv/direnv_test.go
- cmd/init/init.go
- cmd/init/model.go
- cmd/precheck/precheck.go
use:
`bsf direnv` -> initilizes current dir with  .envrc and .gitignore 
`bsf direnv --env key=value` -> sets the env in .envrc
by doing `bsf direnv`  direnv files get loaded in the current dir and whenever user opens shell in the current dir ,
it always opens nix dev shell without specifying any argument
[✔️ ] test locally
> direnv intigration

- cmd/init/config.go
- cmd/init/model.go
- cmd/oci/oci.go
- pkg/nix/template/oci.go
- pkg/update/update.go
* Adds a new template for App OCI builds that have devDeps as true.
* Fixes a runtime error for `bsf init`
> feat: add template for dev oci app builds

- CONTRIBUTORS.md
- cmd/update/update.go
- pkg/update/update.go
- pkg/update/update_test.go
CLOSES #48 
FIXES #48 
This PR adds the functionality to check for updates before updating them through `--check` flag.
> feat: add `--check` flag to the update command

- cmd/dockerfile/df.go
- cmd/oci/oci.go
- pkg/builddocker/build.go
- pkg/builddocker/build_test.go
Fixes #60
Added support for modifying Dockerfiles with tags.
> feat: dockerfile edit

- cmd/build/build.go
- cmd/develop/develop.go
- cmd/dockerfile/df.go
- cmd/init/model.go
- cmd/nixgenerate/model.go
- cmd/oci/oci.go
- cmd/release/release.go
- cmd/update/update.go
- pkg/generate/generate.go
- pkg/hcl2nix/config.go
When a `--tag` flag will be passed with OCI cmd, bsf will rewrite the `bsf.hcl` file with the new tag for the artifact generation.
> fix: oci cmd for tag

- CONTRIBUTORS.md
- cmd/update/update.go
- pkg/hcl2nix/lock.go
- pkg/hcl2nix/lock_test.go
Fixes #28 
- I apologize for the resubmission because the last PR got deleted accidentally. 
- Added my name in CONTRIBUTORS.md
- Made required changes in lock.go and update.go
> fix: Making sure of alphabetical sorting in packages

- bsf.hcl
- bsf.lock
- bsf/flake.nix
- cmd/search/constraints.go
* regenerates lock/flake files post search when package is added. 
* Adds golangci-lint
Functionally, all the bsf commands should still work but a little detail that users might find weird. Thanks to @hanshal101 for reporting on Discord.
> regenerate lock/flake files post search

- cmd/init/config.go
- cmd/oci/oci.go
- pkg/builddocker/build.go
- pkg/generate/generate.go
- pkg/hcl2nix/export.go
- pkg/hcl2nix/lock.go
- pkg/nix/template/oci.go
- pkg/nix/template/oci_test.go
This PR fixes a bug that we saw while creating base images:
* If a user had a package in dev block, but it was not there in the runtime block, it was not being shown in the `flake.nix`, i.e. the flake generation was being wrong for development packages.
> fix: dev pkgs bug in base img

- cmd/update/update.go
- pkg/update/update.go
- pkg/update/update_test.go
Closes #29 
Fixes #29 
This PR adds supports for `non-semver` packages in `bsf update` command.
> feat: add support for bsf update for non-semver packages

- .github/workflows/test.yml
- cmd/direnv/direnv.go
- cmd/init/model.go
- cmd/nixgenerate/model.go
- cmd/precheck/precheck.go
- cmd/search/constraints.go
- cmd/search/model.go
- cmd/search/option.go
- pkg/builddocker/build.go
- pkg/clients/search/search.go
- pkg/hcl2nix/config.go
- pkg/langdetect/langdetect.go
- pkg/nix/cmd/closure.go
- pkg/provenance/provenance.go
- pkg/release/githubRelease.go
- pkg/release/oci.go
- pkg/sbom/sbom.go
- pkg/update/update.go
As discussed with @dr-housemd fixed all the linting errors shown by `golangci-lint run ./...` command.
- All the error which contains unused functions or variables are been commented out in this PR.
- Few changes were added in some conditional statements (test and review required on them)
> fix: fix all lint errors shown in golangci-lint

- cmd/init/config.go
- cmd/init/init.go
- cmd/init/model.go
Closes #74 
Fixes #74 
This PR adds the feature of taking input prompts in the `bsf init` command.
Looks something like this:
```powershell
lol@MSI:$ /bsf/main init
Running prechecks...
✅ Nix version is v2.21.2
✅ Flakes are enabled
Prechecks ran successfully
Do you want docker file to be initialized (y/N) y
What should the name be? : myapp
```
> feat: add input prompts for the init command

- cmd/init/config.go
- cmd/init/init.go
- cmd/init/model.go
- cmd/oci/oci.go
- pkg/langdetect/langdetect.go
- pkg/nix/template/templates.go
> fix: init cmd

- cmd/oci/oci.go
- pkg/hcl2nix/config.go
> fix: `bsf.hcl` regeneration for oci tag

- CONTRIBUTORS.md
- cmd/init/config.go
- cmd/init/init.go
- cmd/init/model.go
> Added common dependencies

- cmd/init/config.go
- cmd/oci/oci.go
- go.mod
- pkg/hcl2nix/export.go
- pkg/nix/template/oci.go
- pkg/nix/template/oci_test.go
- pkg/nix/template/templates.go
> feat: oci layering

- cmd/init/config.go
- pkg/strings/set.go
- pkg/strings/set_test.go
Fixes #126 
Closes #126 
This PR sorts the Development and the Runtime packages present in the `bsf.hcl` in alphabetical order.
This works with both when the buildsafe is initialized and when packages are searched and added to the environment.
There might be better way of implementing the `sortPackages` function in the `cmd\init\config.go`.
As the same logic is used on the both cases. We can put this function to `set.go` in `pkg\strings\set.go`
> feat: sort the dev and runtime packages in bsf.hcl

- cmd/search/versionList.go
Fixes #125 
Closes #125 
This PR adds the Date and Time field to the `bsf search` GUI. (Format: 2006-01-02 15:04)
> feat: add the date and time field to the search gui

- cmd/search/versionList.go
Since we added a new column, we didn't consistently use the column length that caused a length mismatch and made it impossible to add a package.
> (bug): fix package selection 
